.TH JCOMPRESS "1" "December 2022" "jcompress 1.0" "User Commands"
.
.SH NAME
jcompress \- all-in-one compression script
.
.SH SYNOPSIS
usage: jcompress [OPTIONS] [-m|--mode MODE] [--] ARCHIVE FILE|DIR...
       jcompress \fB-h\fR|--help
.
.SH DESCRIPTION
jcompress is a convenvience script for interfacing with different archiving programs.
The options listed below are translated to their counterparts in the selected archive program.
.
.IP "Valid Extensions:"
zip (.zip),
7z (.7z),
tgz (.tgz, .tar.gz),
tbz2 (.tbz2, .tar.bz2),
t7z (.t7z, .tar.7z)
.
.IP "Valid Modes:"
The
.B --mode
option accepts any of the valid extensions as argument, minus the leading dot.
For example, `--mode tar.gz' is a valid format.
.
.SH OPTIONS
Options that are mandatory for short options are mandatory for long options as well.
.
.TP
.B -h
.TQ
.B --help
Display this help message and exit.
.
.TP
.B -V
.TQ
.B --version
Print the program version and exit.
.
.TP
.BI -m\~ mode
.TQ
.B --mode
Specifiy the mode (or format) of the archive.
If omitted, the archive's extension is used.
.
.TP
.B --use-pigz
For the tgz format, this specifies pigz as the compression program to use.
.
.TP
.B --use-pbzip2
For the tbz2 format, this specifies pbzip2 as the compression program to use.
.
.TP
.B --password
Encrypt the archive with a password.
What happens exactly will depend on the format.
.
.TP
.B -r
.TQ
.B --recursive
Travel subdirectories recursively.
This option is ignored for some programs, like 7z.
.
.TP
.B -M
.TQ
.B --move
Move the files into the archive.
Actually, the files are simply deleted after copying them.
.
.SH PASSWORDS
What --password does depends on the archive type.
Zip files have the -e option, which prompts for user input.
Tar-derived files (e.g., .tar.gz) are encrypted using gpg.
For it to work, the user must set
.B JC_GPGPUBKEY
to the public key they want to use.
The actual command used is:
.IP
gpg --encrypt --recipient $JC_GPGPUBKEY "$archive" && rm -v "$archive"
.
.PP
7z files have the -p option to set a password, but the password is specified directly on the command line.
jcompress actually defines its own function to prompt the user for a password, and it is passed to this option.
For reference, the commandline to encrypt a 7z file with a password looks like this:
.IP
7z a -pPASSWORD archive.7z ...
.
.SH "ENVIRONMENT VARIABLES"
.IP JC_GPGPUBKEY
For formats that use gpg to encrypt the file, this
holds the public key to use.
.
.SH "SEE ALSO"
.BR 7z (1),\~ tar (1),\~ zip (1),\~ pigz (1),\~ pbzip2 (1),\~ gpg (1)
