#!/bin/bash

usage() {
    echo "$HELP" | head -n 2
}

declare -r BASENAME=${0##*/}
declare -r VERSION="$BASENAME [VERSION]"

declare -r HELP=$(cat <<EOF
usage: $BASENAME [-lv] ARCHIVE
       $BASENAME [-h|-V]

Options:
       -h
       --help Print this help message and exit.

       -V
       --version
              Print the program version and exit.

       -l
       --list List the contents of ARCHIVE.

       -v
       --verbose
	      The output will be more detailed.
EOF
	)

tmp=$(mktemp)
trap "rm $tmp" EXIT

# Parse commandline options
# If getopt returns true, noop, otherwise an error is generated
if temp=$(getopt -o 'hVlv' -l 'help,version,list,verbose' -- "$@" 2>$tmp); then
    # good
    :
else
    echo -e "$BASENAME:`cat $tmp`" >&2
    usage
    exit 1
fi
eval set -- "$temp"

while true; do
    case "$1" in
	-h|--help)
	    echo "$HELP"
	    exit
	    ;;
	-V|--version)
	    echo $VERSION
	    exit
	    ;;
	-l|--list)
	    DOLIST=1
	    shift
	    ;;
	-v|--verbose)
	    DOVERBOSE=1
	    shift
	    ;;
	--)
	    shift
	    break
	    ;;
	*)
	    echo '$BASENAME: internal error' >&2
	    exit 1
    esac
done

# Archive not provided
archive="$1"
if [ -z "$archive" ]; then
    echo "$BASENAME: missing filename" >&2
    usage
    exit 1
elif [ ! -f "$archive" ]; then
    echo "$BASENAME: $archive does not exist" >&2
    usage
    exit 1
fi

case "$archive" in
    *.zip)
	unzip "$archive"
	;;
    *.tar.gz|*.tgz)
	tar xzf "$archive"
	;;
    *.tar.bz2|*.tbz2)
	tar xjf "$archive"
	;;
    *.tar.xz)
	tar xJf "$archive"
	;;
    *.tar.7z)
	7za x -so "$archive" | tar xf -
	;;
    *.gz)
	gunzip "$archive"
	;;
    *.bz2)
	bunzip2 "$archive"
	;;
    *.tar)
	tar xf "$archive"
	;;
    *.7z)
	7z x "$archive"
	;;
    *)
	echo "$BASENAME: $archive not supported by extract()" >&2
	exit 1
esac
